name: Bug report
description: 缺陷问题反馈
labels: [bug]
body:
  - type: textarea
    id: symptom
    attributes:
      label: 问题现象
      description: 实际表现（截图/录屏/日志）
  - type: textarea
    id: expected
    attributes:
      label: 期望结果
  - type: textarea
    id: repro
    attributes:
      label: 复现步骤
      value: |-
        1. 
        2. 
        3. 
  - type: input
    id: env
    attributes:
      label: 环境信息
      placeholder: 设备/系统、App 版本、网络/权限
  - type: input
    id: priority
    attributes:
      label: 优先级
      placeholder: P0/P1/P2
  - type: textarea
    id: trace
    attributes:
      label: 日志/堆栈/排查
  - type: checkboxes
    id: verify
    attributes:
      label: 验证用例
      options:
        - label: 用例1
        - label: 用例2

