name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ios-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: macos-14
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'
      - name: Install SwiftLint
        run: brew install swiftlint
      - name: SwiftLint AutoCorrect (non-blocking)
        run: |
          if [ -f .swiftlint.yml ]; then
            swiftlint autocorrect --format --config .swiftlint.yml || true
          fi
      - name: SwiftLint Strict
        run: swiftlint lint --config .swiftlint.yml --strict
      - name: (Optional) Analyzer Rules
        if: ${{ github.event_name == 'pull_request' }}
        run: swiftlint analyze --config .swiftlint.yml || true

  build-test:
    needs: lint
    runs-on: macos-14
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'
      - name: Cache SPM
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            ~/.swiftpm
          key: spm-${{ runner.os }}-${{ hashFiles('**/Package.resolved') }}
          restore-keys: spm-${{ runner.os }}-
      - name: Build & Test
        run: |
          set -eo pipefail
          xcodebuild -scheme SafeDriverNote -destination 'platform=iOS Simulator,name=iPhone 15' clean test | xcpretty
      - name: Store Logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            build/reports
            ~/Library/Logs/DiagnosticReports
          if-no-files-found: ignore
